apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8sadmin-binding
subjects:
- kind: User
  name: k8sadmin 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io