apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata: 
 name: csr-for-k8sadmin
spec: 
 groups: 
 - "system:authenticated"
 usages: 
 - client auth
 - digital signature
 - key encipherment
 signerName: kubernetes.io/kube-apiserver-client
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dEQ0NBVUFDQVFBd0V6RVJNQThHQTFVRUF3d0lhemh6WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFgzRHVQTC8vTGpIRHA3UmswVCtNRElrNHRScGlDL3BwZVZ6cUsxOHd5CkkyNXZ4VnRVUmxUMHNqbWYvU20yS3AxWnpNY3VhUS9UclQ2T0p4cVl6OUpGSTJFdnpTalRkL25qNVpaSkx5cjkKSmdncjdZUzFTRy85ZDBGTlpWMUtPNDB4QjlVTS9uRTk3ajJHd0dFdnUxQW1qbkR6Q0owdUppMStGbVh2RkN3Rwo0bDhVVktIZEZGVjBwbEJLRFhqRFQ4ckt2OUd2T0dlWmlQbGxVbW1KbkZPTWt6NUxxSzQ5RzFxaWEvUnJ5U0xjCjA1ZnVUSkttQjBHdllBME80VUd3YmhCaTUxRFdsZGd6V09OdHN0YzZSSGRvanU0WjN4Y0FBWkZtWGd1Q2pGbWMKUnVIcWNQYTRGaHBKOTBRbjM4ZG9icVRvbUJuejRvMm1ocFVycXAxaHgvdjlBZ01CQUFHZ0FEQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBd0lqbU91TUNHM25uWmZxeHhkY3Q5eVI3Ky9qV2dMYXNneEdKbkFWRzFKMjdvQnd3Cjdlb0k5ZGx4TXBFa0FEZEliOWt5ZHlhQlJvSC9qSXlmQTlHTndySFA1RGNhQ1UrbUpZb0pmNCtkYmZnQ3Zzc1AKVDBZUkFvaE9sdk1YSVRaQlA2djViZXhGdkEveHg2QnhsZWRsR3dKTGpvVFhnUTdGL0VsTVZiNG8rZ1h2YWs0RApTeW9CNDNZcEdnbEYzZ1owN09tNDU2OUxnSTBqTlNJai9ZUExSaXNwZ2R0UHFkVytwZzZjaStPSUl3N21VMFBYClp4dTZnS2NXOU1iN0psT21ickdIR2hEcmRkUmVCQmJaQjZRZGVNbTZWSG9QaHNYWHRmTVFndFJqSVJDTjVONlQKNEQzMFJwUFVYYVZ5b0NBdmdOUm5lbEdXWnNzOEtkZzVBaHBCeWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K