apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
spec:
  selector:
    matchLabels:
      run: payment-app
  replicas: 1
  template:
    metadata:
      labels:
        run: payment-app
    spec:
      containers:
      - name: payment-app
        image: nickholbrook/gs-accessing-data-mysql:v7
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      tolerations:
      - key: ""
        operator: "Exists"
        effect:
---

apiVersion: v1
kind: Service
metadata:
  name: payment-app
  labels:
    app: payment-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: payment-app

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: payment-app
  name: payment-app
spec:
  rules:
  - host: payment-app.com
    http:
      paths:
      - backend:
          serviceName: payment-app
          servicePort: 8080
        path: /