apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: allow-web-to-db
spec:
 podSelector:
  matchLabels:
   app: db              # target
 policyTypes:
 - Ingress
 ingress:
 - from:
   - podSelector:
      matchLabels:
        app: web        # source
   ports:
   - port: 80           # change port no.